# Generated by Django 3.2.21 on 2024-03-27 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('ph_no', models.BigIntegerField()),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='distributor_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='distributor_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('ph_no', models.BigIntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('proof', models.FileField(upload_to='')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='manufacture_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('date', models.DateField()),
                ('size', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=20)),
                ('pin', models.BigIntegerField()),
                ('ph_no', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='shop_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('ph_no', models.BigIntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('proof', models.FileField(upload_to='')),
                ('email', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='shop_req_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('DISTRIBUTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.distributor_table')),
                ('SHOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.shop_table')),
            ],
        ),
        migrations.CreateModel(
            name='shop_req_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.manufacture_product')),
                ('SHOP_MASTER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.shop_req_master')),
            ],
        ),
        migrations.CreateModel(
            name='shop_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('DISTRIBUTOR_PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.distributor_product')),
            ],
        ),
        migrations.CreateModel(
            name='shop_bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('SHOP_PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.shop_product')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('photo', models.FileField(upload_to='')),
                ('price', models.FloatField()),
                ('size', models.CharField(max_length=60)),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.category')),
            ],
        ),
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.order')),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.shop_req_details')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.user_table'),
        ),
        migrations.CreateModel(
            name='manufacturer_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('ph_no', models.BigIntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('proof', models.FileField(upload_to='')),
                ('email', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.login_table')),
            ],
        ),
        migrations.AddField(
            model_name='manufacture_product',
            name='MANFACTURER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.manufacturer_table'),
        ),
        migrations.AddField(
            model_name='manufacture_product',
            name='PRODUCT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.product'),
        ),
        migrations.AddField(
            model_name='distributor_table',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.login_table'),
        ),
        migrations.CreateModel(
            name='distributor_req_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('DISTRIBUTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.distributor_table')),
                ('MANFACTURER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.manufacturer_table')),
            ],
        ),
        migrations.CreateModel(
            name='distributor_req_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('DISTRIBUTOR_MASTER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.distributor_req_master')),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.manufacture_product')),
            ],
        ),
        migrations.AddField(
            model_name='distributor_product',
            name='DISTRIBUTOR_REQUEST',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.distributor_req_details'),
        ),
        migrations.CreateModel(
            name='bill_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('BILL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.bill')),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.product')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='SHOP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.shop_table'),
        ),
    ]
