# Generated by Django 3.2.21 on 2024-03-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fake_product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill_details',
            name='BILL',
        ),
        migrations.RemoveField(
            model_name='bill_details',
            name='PRODUCT',
        ),
        migrations.DeleteModel(
            name='bill',
        ),
        migrations.DeleteModel(
            name='bill_details',
        ),
    ]
