# Generated by Django 3.2.21 on 2024-03-27 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fake_product', '0002_auto_20240327_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('ph_no', models.BigIntegerField()),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('SHOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.shop_table')),
            ],
        ),
        migrations.CreateModel(
            name='bill_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('BILL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.bill')),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.product')),
            ],
        ),
    ]
