# Generated by Django 3.2.21 on 2024-03-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_product', '0003_bill_bill_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
