# Generated by Django 3.2.21 on 2024-04-02 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fake_product', '0005_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='return_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(max_length=30)),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fake_product.order_details')),
            ],
        ),
        migrations.DeleteModel(
            name='shop_bill',
        ),
    ]
