# Generated by Django 3.2.21 on 2024-04-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_product', '0006_auto_20240402_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gst',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
