# Generated by Django 3.2.21 on 2024-04-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_product', '0007_order_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='return_table',
            name='status',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
