# Generated by Django 5.0.4 on 2024-04-05 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_product', '0008_return_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_product',
            name='SHOP',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fake_product.shop_table'),
            preserve_default=False,
        ),
    ]
