# Generated by Django 5.0.4 on 2024-04-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fake_product', '0009_shop_product_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
